### ISSUE TITLE
[Bug] Out of bounds error

### ISSUE THREAD

**Issue by alexmozaidze** [AntMCDev/MCLangSplitFabric#2]
Minecraft doesn't crash; instead, it spams logs with this text and doesn't let minecraft load properly (index increases infinitely)
```log
[21:45:16] [Render thread/ERROR]: Index 84786 out of bounds for length 0; Активные боссбары отсутствуют ამოღებულია პერსონალური ბოსბარი%s
```
Main language: Russian
Secondary language: Georgian
Mod list: https://pastebin.com/4rJeGDbs

**Comment by AntMCDev** [comment]
Hi, thanks for bringing this to my attention. This issue should now be resolved in the latest version of the mod on Curseforge (v1.0.1).
