### ISSUE TITLE
[Feature Request] Add option to quick-switch languages

### ISSUE THREAD

**Issue by alexmozaidze** [AntMCDev/MCLangSplitFabric#5]
Add an option that makes it so that only 1 language is shown at a time, but when you press a keybind it switches to other language. I've noticed that many buttons just can't fit the text when using Russian+Georgian.

**Comment by AntMCDev** [comment]
I've uploaded v1.0.3 to Curseforge, which should enable this option in most places (Minecraft has a lot of different areas that handle things in different ways - so sometimes tricky to hit all the areas in one go).

Default keybind is "r", but you can change that in the Minecraft controls area, as usual. It will cycle through Original Language, Alternate Language and Both respectively.

There's a new option in the config you can use to turn this feature on (you'll need to manually set that, as I've set it to false by default):
enableExperimentalFeatures = true

If there are any issues, feel free to reply to this thread - I haven't tested it much yet, but seemed to work in most places.
